version: '3.8'

services:
  ecopulse-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: ecopulse-app
    environment:
      - NODE_ENV=production
